### ISSUE TITLE
ERROR synology_logger unknown type byte 0xBC

### ISSUE THREAD

**Issue by Nacionarte** [anojht/synology-cloud-sync-decrypt-tool#27]
Hi,
I'm getting errors and my impression is it like/folder related rather than the tool itself.. Check logs:
2022-12-30 13:53:46,588 INFO syndecrypt.files decrypting "/Users/User1/Desktop/BAK/@Projects@/ECRYPTFS_FNEK_ENCRYPTED.FWbELhHcZphxBUbzIZ66nWLjEID.ZR2E1Dc9dFnaOhqa1V9r20EoYgsMoU--" to "/Users/User1/Desktop/BAK/@Projects@/Test-decryption-mac-Syno-tool/ECRYPTFS_FNEK_ENCRYPTED.FWbELhHcZphxBUbzIZ66nWLjEID.ZR2E1Dc9dFnaOhqa1V9r20EoYgsMoU--"
2022-12-30 13:53:46,595 ERROR syndecrypt.core magic should not be b'\x00\x00\x00\x00\x00\x008\x04=\xc6\x02X\x01G\xb5\xad\x03' but b'__CLOUDSYNC_ENC__'
2022-12-30 13:53:46,596 ERROR syndecrypt.core magic hash should not be b'\x00\x00\n\x00\x00\x10\x00\x00\x02\x8c-\x04\t\x03\x01\x00\x11"3DUfw`\xdeo\xc0\xdf\x17\xe3yf' but b'd8d6ba7b9df02ef39a33ef912a91dc56'
2022-12-30 13:53:46,949 ERROR syndecrypt.files decryption failed, exception occurred: <class 'Exception'>: unknown type byte 0xBC
2022-12-30 13:53:46,949 ERROR synology_logger unknown type byte 0xBC
Traceback (most recent call last):
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/Synology.py", line 204, in validate
    run_tool()
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/Synology.py", line 307, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 200, in decrypt_stream
    for (key,value) in decode_csenc_stream(instream):
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 173, in decode_csenc_stream
    for obj in _read_objects_from(f):
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 109, in _read_objects_from
    obj = _read_object_from(f)
  File "/Users/User1/Downloads/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 129, in _read_object_from
    raise Exception('unknown type byte ' + ("0x%02X" % header_byte))
Exception: unknown type byte 0xBC

**Comment by anojht** [comment]
Hi, thanks for the report. I had a look at your log and this isn't actually a bug in the tool; it's a file-type mismatch.

Your file is named `ECRYPTFS_FNEK_ENCRYPTED.FWbELhHcZphxBUbzIZ66nWLjEID.….` The `ECRYPTFS_FNEK_ENCRYPTED.` prefix means it's an eCryptfs-encrypted file, which is what Synology uses for its encrypted shared folders (DSM home directory encryption, encrypted shares, etc.). That's a completely different encryption system from Synology Cloud Sync.

This tool only decrypts Cloud Sync output, files that start with the magic bytes `CLOUDSYNC_ENC.` The log line confirms the mismatch:

  `ERROR syndecrypt.core magic should not be b'\x00\x00\x00\x00…' but b'CLOUDSYNC_ENC'`

  The tool sees the wrong magic header, logs the error, and then crashes further down the parser with the misleading unknown type byte 0xBC.

  To decrypt eCryptfs files from a Synology encrypted shared folder, you have two options:

  - Mount the share back on the Synology NAS with the original encryption key, or
  - Use ecryptfs-utils on a Linux machine with the share's encryption key loaded

Neither of those is something this tool can do. Closing as not-a-bug.  But I'll track the cryptic error message as a separate UX improvement so the next person who hits this gets a clearer hint right away. Hope you manage to recover your files!
