### ISSUE TITLE
Password decryption fails

### ISSUE THREAD

**Issue by transistorgit** [anojht/synology-cloud-sync-decrypt-tool#6]
Decryption with key works, but not with password

2019-03-13 21:22:08,030 INFO syndecrypt.files decrypting "/Users/bernd/Downloads/OneDrive-2019-03-13/2018_12_26 17_06_02 0 Daggiphone.jpg" to "/Users/bernd/Downloads/onedrive decrypted/2018_12_26 17_06_02 0 Daggiphone.jpg"
2019-03-13 21:22:08,030 WARNING syndecrypt.core found key1_hash T21v0aVx3R86b309771ca9f9be2daaed390f83bee2 but expected T21v0aVx3R12478a2c7aaa372f87ea55ccbebd8e68
2019-03-13 21:22:08,038 ERROR syndecrypt.files decryption failed, exception occurred: <class 'ValueError'>: invalid padding byte at end of b'\xf6;\xb8\xdd\x96X\x8b`\x05\xa6yh\xea&\xc1\xfb\xa8i`\xf3\xf2O\x84P\xe7\xda\xffV\xa1\x84Q\x95'
2019-03-13 21:22:08,038 ERROR synology_logger invalid padding byte at end of b'\xf6;\xb8\xdd\x96X\x8b`\x05\xa6yh\xea&\xc1\xfb\xa8i`\xf3\xf2O\x84P\xe7\xda\xffV\xa1\x84Q\x95'
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/bernd/synology-cloud-sync-decrypt-tool/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/bernd/synology-cloud-sync-decrypt-tool/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/bernd/synology-cloud-sync-decrypt-tool/syndecrypt/core.py", line 219, in decrypt_stream
    session_key = decrypted_with_password(base64.b64decode(header['enc_key1'].encode('ascii')), password, header['salt'].encode('ascii'))
  File "/Users/bernd/synology-cloud-sync-decrypt-tool/syndecrypt/core.py", line 73, in decrypted_with_password
    plaintext = decryptor_update(decryptor, ciphertext)
  File "/Users/bernd/synology-cloud-sync-decrypt-tool/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/bernd/synology-cloud-sync-decrypt-tool/syndecrypt/core.py", line 64, in strip_PKCS7_padding
    raise ValueError("invalid padding byte at end of " + repr(data[-32:]))
ValueError: invalid padding byte at end of b'\xf6;\xb8\xdd\x96X\x8b`\x05\xa6yh\xea&\xc1\xfb\xa8i`\xf3\xf2O\x84P\xe7\xda\xffV\xa1\x84Q\x95'

As key decryption works, this is fine for me. But mayby I can help to find the bug?

**Comment by anojht** [comment]
Hello, have you ensured you are typing the password correctly? It seems to be working fine for me with my latest test.

**Comment by transistorgit** [comment]
hmm, just copies the password from my keepass. Need to install Syno tool to crosscheck

**Comment by anojht** [comment]
I am going to close this as I cannot replicate this issue. Please reopen after your crosscheck if there is still an issue.
