### ISSUE TITLE
Password decryption failure - Size does not fit in an int

### ISSUE THREAD

**Issue by khalestorm** [anojht/synology-cloud-sync-decrypt-tool#8]
Unable to decrypt a file that I uploaded and downloaded from my Gsuite account. Error log below

```2019-05-13 17:04:49,786 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv"
2019-05-13 17:05:17,184 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 17:05:17,190 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 17:09:19,793 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv"
2019-05-13 17:09:57,340 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 17:09:57,343 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 17:10:12,955 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan(1).mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan(1).mkv"
2019-05-13 17:10:32,690 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 17:10:32,691 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 17:56:10,790 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan(1).mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan(1).mkv"
2019-05-13 17:56:41,204 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 17:56:41,208 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 17:57:27,976 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv"
2019-05-13 17:57:47,542 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 17:57:47,543 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 18:01:35,890 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv"
2019-05-13 18:01:54,221 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 18:01:54,222 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 18:02:07,995 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan(1).mkv" to "/Users/kyle/Desktop/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan(1).mkv"
2019-05-13 18:02:26,591 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 18:02:26,592 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
2019-05-13 20:09:02,952 INFO syndecrypt.files decrypting "/Users/kyle/Downloads/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv" to "/Users/kyle/Documents/Borat Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan.mkv"
2019-05-13 20:09:35,267 ERROR syndecrypt.files decryption failed, exception occurred: <class 'OverflowError'>: size does not fit in an int
2019-05-13 20:09:35,270 ERROR synology_logger size does not fit in an int
Traceback (most recent call last):
  File "Synology.py", line 199, in validate
    run_tool()
  File "Synology.py", line 302, in run_tool
    __main__.main(['-p', pword, out, input])
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/__main__.py", line 96, in main
    files.decrypt_file(ff, os.path.join(output_dir, fp), password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/files.py", line 28, in decrypt_file
    core.decrypt_stream(instream, outstream, password=password, private_key=private_key, public_key=public_key)
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 240, in decrypt_stream
    decrypted_data = decryptor_update(decryptor, bytes(data))
  File "/Users/kyle/bin/synology-cloud-sync-decrypt-tool-master/syndecrypt/core.py", line 94, in decryptor_update
    return strip_PKCS7_padding(decryptor.decrypt(ciphertext))
  File "/Users/kyle/syndecrypt-venv/lib/python3.7/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
OverflowError: size does not fit in an int
```

**Comment by anojht** [comment]
This error seems to be thrown when the file size is large and it exceeds the memory buffer, I am still investigating, thanks for reporting this!

**Comment by khalestorm** [comment]
Thanks for the quick response. I'd love to get this working on my machine. Currently, I'm trying to use Wine to run the windows app, but would much prefer to use yours :)

**Comment by anojht** [comment]
Sorry for the delay, please try the latest version. I tested decryption with a 4GB test file and it was successful!

**Comment by anojht** [comment]
I am going to close this due to lack of response. The bug has been fixed in the latest version and tested working.
